site:
  title: Reference Notes
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://antora.gitlab.io/demo/docs-site
  start_page: techDocs::index.adoc
content:
  sources:
    - url: ../docs
      start_paths:
        - notes/techDocs
        - notes/cloud
        - notes/interview
      branches:
        - 'HEAD'
ui:
  bundle:
    #url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.3.5/ui-bundle.zip
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    # url: https://github.com/fabianfnc/bocs/blob/master/doc/uibundle.zip?raw=true
    #url: _antora/ui-bundle.zip
    snapshot: true
  supplemental_files: _antora/supplemental_ui
  output_dir: antora
antora:
  extensions:
    - require: '@antora/lunr-extension'

runtime:
  fetch: true
  cache_dir: ./.cache/antora
  log:
    failure_level: error

# Global asciidoc attributes here, used across all versions of documentation
asciidoc:
  extensions:
    - asciidoctor-kroki
    # Antora will resolve extensions listed here that end with something that looks like a file name extension as files relative to the project's folder
    # therefore append the slash
    - asciidoctor-highlight.js/
  attributes:
    kroki-fetch-diagram: true
    idprefix: ''
    idseparator: '-'
    source-highlighter: highlightjs-ext

output:
  clean: true
  # dir: _site/docs
