= Classes And Interfaces
:navtitle: Classes And Interfaces
:description: Classes and Interfaces are basic units of abstractions in Java.

{description}


== Item 15: Minimize the accessibility of classes and members
* A well-designed component hides all its implementation details, cleanly separating its API from its implementation. Components then communicate only through their APIs and are oblivious to each others’ inner workings. This concept, known as *information hiding* or *encapsulation*, is a fundamental tenet of software design.

* Information hiding is important for many reasons, most of which stem from the fact that it *decouples* the components that comprise a system, allowing them to be developed, tested, optimized, used, understood, and modified in isolation. 

* Information hiding increases software reuse because components that aren’t tightly coupled often prove useful in other contexts besides the ones for which they were developed.

*Java has many facilities to aid in information hiding.* 
The *access control mechanism* specifies the *accessibility* of classes, interfaces, and members. 

For members (fields, methods, nested classes, and nested interfaces), there are four possible access levels, listed here in order of increasing accessibility:

• private—The member is accessible only from the top-level class where it is declared.

• package-private—The member is accessible from any class in the package where it is declared. Technically known as package access, this is the access level you get if no access modifier is specified (except for interface members, which are public by default).

• protected—The member is accessible from subclasses of the class where it is declared (subject to a few restrictions [JLS, 6.6.2]) and from any class in the package where it is declared.

• public—The member is accessible from anywhere.


*Instance fields of public classes should rarely be public* 

[IMPORTANT]
====
A nonzero-length array is always mutable, so it is wrong for a class to have a `public static final` array field, or an accessor that returns such a field. If a class has such a field or accessor, clients will be able to modify the contents of the array. This is a frequent source of security holes
====


*As of Java 9, there are two additional, implicit access levels introduced as part of the module system*. A module is a grouping of packages, like a package is a grouping of classes. A module may explicitly export some of its packages via export declarations in its module declaration (which is by convention contained in a source file named module-info.java). Public and protected members of unexported packages in a module are inaccessible outside the module; within the module, accessibility is unaffected by export declarations. Using the module system allows you to share classes among packages within a module without making them visible to the entire world. Public and protected members of public classes in unexported packages give rise to the two implicit access levels, which are intramodular analogues of the normal public and protected levels. The need for this kind of sharing is relatively rare and can often be eliminated by rearranging the classes within your packages.

[NOTE]
====
If you place a module’s JAR file on your application’s class path instead of its module path, the packages in the module revert to their non-modular behavior: all of the public and protected members of the packages’ public classes have their normal accessibility, regardless of whether the packages are exported by the module. The one place where the newly introduced access levels are strictly enforced is the JDK itself: the unexported packages in the Java libraries are truly inaccessible outside of their modules.
====

---

== Item 16: In public classes, use accessor methods, not public fields
[source, java]
----
// Degenerate classes like this should not be public!
class Point {
    public double x;
    public double y;
}
----
* If a class is accessible outside its package, provide accessor methods to preserve the flexibility to change the class’s internal representation. If a public class exposes its data fields, all hope of changing its representation is lost because client code can be distributed far and wide.

* If a class is package-private or is a private nested class, there is nothing inherently wrong with exposing its data fields

* *public classes should never expose mutable fields.* It is less harmful, though still questionable, for public classes to expose immutable fields. 

* It is, however, sometimes desirable for package-private or private nested classes to expose fields, whether mutable or immutable.

---

== Item 17: Minimize Mutability

* *An immutable class is simply a class whose instances cannot be modified. All of the information contained in each instance is fixed for the lifetime of the object, so no changes can ever be observed.* 

The Java platform libraries *contain many immutable classes*, including `String`, *the boxed primitive classes*, and `BigInteger` and `BigDecimal`. 

* Immutable classes are easier to design, implement, and use than mutable classes. They are less prone to error and are more secure.

[IMPORTANT]
.To make a class immutable, follow these five rules:
====
1. *Don’t provide methods that modify the object’s state* (known as mutators).

2. *Ensure that the class can’t be extended.* 

3. *Make all fields final.* 

4. *Make all fields private.*

5. *Ensure exclusive access to any mutable components.* 
====

[source,java]
----
// Immutable complex number class
public final  class Complex {
    private final  double re;
    private final  double im;

    public Complex(double re, double im) {
        this.re = re;
        this.im = im;
    }

    public double realPart()      { return re; }
    public double imaginaryPart() { return im; }

// Below pattern is known as the functional approach because 
// below arthmetic methods return the result of applying 
// a function to their operand, without modifying it and returning
// a new object.
    public Complex plus(Complex c) {
        return new Complex(re + c.re, im + c.im);
    }

    public Complex minus(Complex c) {
        return new Complex(re - c.re, im - c.im);
    }

    public Complex times(Complex c) {
        return new Complex(re * c.re - im * c.im,
                           re * c.im + im * c.re);
    }

    public Complex dividedBy(Complex c) {
        double tmp = c.re * c.re + c.im * c.im;
        return new Complex((re * c.re + im * c.im) / tmp,
                           (im * c.re - re * c.im) / tmp);
    }

    @Override public boolean equals(Object o) {
       if (o == this)
           return true;
       if (!(o instanceof Complex))
           return false;
       Complex c = (Complex) o;

       // See page 47 to find out why we use compare instead of ==
       return Double.compare(c.re, re) == 0
           && Double.compare(c.im, im) == 0;
    }
    @Override public int hashCode() {
        return 31 * Double.hashCode(re) + Double.hashCode(im);
    }

    @Override public String toString() {
        return "(" + re + " + " + im + "i)";
    }
}
----


The *functional approach* may appear unnatural if you’re not familiar with it, but it *enables immutability*, which has many advantages. 

* *Immutable objects are simple.* 

* *Immutable objects are inherently thread-safe; they require no synchronization.* 

* *Not only can you share immutable objects, but they can share their internals.* 

* *Immutable objects make great building blocks for other objects.*

* *Immutable objects provide failure atomicity for free* (Item 76). Their state never changes, so there is no possibility of a temporary inconsistency.

*The major disadvantage of immutable classes is that they require a separate object for each distinct value.* which comes with a cost.
[source,java]
----
BigInteger moby = ...;
moby = moby.flipBit(0);
----

The `flipBit` method creates a new `BigInteger` instance, also a million bits long, that differs from the original in only one bit. The operation requires time and space proportional to the size of the `BigInteger`. Contrast this to java.util.BitSet. Like `BigInteger`, BitSet represents an arbitrarily long sequence of bits, but unlike `BigInteger`, BitSet is mutable. The BitSet class provides a method that allows you to change the state of a single bit of a million-bit instance in constant time:
[source,java]
----
BitSet moby = ...; moby.flip(0);
----



*Resist the urge to write a setter for every getter. Classes should be immutable unless there’s a very good reason to make them mutable.* 

* If a class cannot be made immutable, limit its mutability as much as possible. 

---

== Item 18: Favor Composition over Inheritance
Inheritance is a powerful way to achieve code reuse, *but it is not always the best tool for the job.* 

* It is safe to use inheritance within a package, where the subclass and the superclass implementations are under the control of the same programmers. 

* It is also safe to use inheritance when extending classes specifically designed and documented for extension (Item 19). 

[NOTE]
====
The problems discussed in this item do not apply to interface inheritance.
====

*Unlike method invocation, inheritance violates encapsulation* A subclass depends on the implementation details of its superclass for its proper function. The superclass’s implementation may change from release to release, and if it does, the subclass may break, even though its code has not been touched.

[source, java]
----
Click here to view code image

// Broken - Inappropriate use of inheritance!
public class InstrumentedHashSet<E> extends HashSet<E> {
    // The number of attempted element insertions
    private int addCount = 0;

    public InstrumentedHashSet() {
    }

    public InstrumentedHashSet(int initCap, float loadFactor) {
        super(initCap, loadFactor);
    }
    @Override public boolean add(E e) {
        addCount++;
        return super.add(e);
    }
    @Override public boolean addAll(Collection<? extends E> c) {
        addCount += c.size();
        return super.addAll(c);
    }
    public int getAddCount() {
        return addCount;
    }
}

InstrumentedHashSet<String> s = new InstrumentedHashSet<>();
s.addAll(List.of("Snap", "Crackle", "Pop"));

s.getAddCount(); // return result as 6.

----
Internally, HashSet’s `addAll` method is implemented on top of its `add` method, although `HashSet`, quite reasonably, does not document this implementation detail. The `addAll` method in *Instrumented-HashSet* added three to `addCount` and then invoked HashSet’s `addAll` implementation using `super.addAll`. This in turn invoked the `add` method, as *overridden* in `InstrumentedHashSet`, once for each element. *Each of these three invocations added one more to addCount, for a total increase of six: each element added with the addAll method is double-counted*.

There is a way to avoid the problems caused y *inheritance*. *Instead of extending an existing class, give new class a private field that references an instance of the existing class.* This design is called *composition* because *the existing class becomes a component of the new one*. 

Each instance method in the new class invokes the corresponding method on the contained instance of the existing class and returns the results. *This is known as forwarding, and the methods in the new class are known as forwarding methods.* 

[source,java]
----
// Wrapper class - uses composition in place of inheritance
public class InstrumentedSet<E> extends ForwardingSet<E> {
    private int addCount = 0;

    public InstrumentedSet(Set<E> s) {
        super(s);
    }

    @Override public boolean add(E e) {
        addCount++;
        return super.add(e);
     }
     @Override public boolean addAll(Collection<? extends E> c) {
         addCount += c.size();
         return super.addAll(c);
     }
     public int getAddCount() {
         return addCount;
     }
}
----

// Reusable forwarding class
public class ForwardingSet<E> implements Set<E> {
    private final Set<E> s; // create component set.
    public ForwardingSet(Set<E> s) { this.s = s; }

    public void clear()               { s.clear();            }
    public boolean contains(Object o) { return s.contains(o); }
    public boolean isEmpty()          { return s.isEmpty();   }
    public int size()                 { return s.size();      }
    public Iterator<E> iterator()     { return s.iterator();  }
    public boolean add(E e)           { return s.add(e);      }
    public boolean remove(Object o)   { return s.remove(o);   }
    public boolean containsAll(Collection<?> c)
                                   { return s.containsAll(c); }
    public boolean addAll(Collection<? extends E> c)
                                   { return s.addAll(c);      }
    public boolean removeAll(Collection<?> c)
                                   { return s.removeAll(c);   }
    public boolean retainAll(Collection<?> c)
                                   { return s.retainAll(c);   }
    public Object[] toArray()          { return s.toArray();  }
    public <T> T[] toArray(T[] a)      { return s.toArray(a); }
    @Override public boolean equals(Object o)
                                       { return s.equals(o);  }
    @Override public int hashCode()    { return s.hashCode(); }
    @Override public String toString() { return s.toString(); }
}
---

* The `InstrumentedSet` class *is known as a wrapper class because each `InstrumentedSet` instance contains (“wraps”) another `Set` instance.* 

* This is also known as the *Decorator pattern* [Gamma95] because the `InstrumentedSet` class “decorates” a set by adding instrumentation. 

* Sometimes *the combination of composition and forwarding is loosely referred to as delegation*. 


* *Disadvantages of wrapper classes are few*. 
** Wrapper classes are not suited for use in callback frameworks, wherein objects pass self-references to other objects for subsequent invocations (“callbacks”). Because a wrapped object doesn’t know of its wrapper, it passes a reference to itself (this) and callbacks elude the wrapper. This is known as the *SELF problem* [Lieberman86]. 
** Some people worry about the performance impact of forwarding method invocations or the memory footprint impact of wrapper objects. Neither turn out to have much impact in practice. It’s tedious to write forwarding methods, but you have to write the reusable forwarding class for each interface only once, and forwarding classes may be provided for you. For example, Guava provides forwarding classes for all of the collection interfaces [Guava].

* *Inheritance is appropriate only in circumstances where the subclass really is a subtype of the superclass.* 
** In other words, a class B should extend a class A only if an *“is-a”* relationship exists between the two classes. 
** There is one last set of questions you should ask yourself before deciding to use inheritance in place of composition. Does the class that you contemplate extending have any flaws in its API? If so, are you comfortable propagating those flaws into your class’s API? *Inheritance propagates any flaws in the superclass’s API, while composition lets you design a new API that hides these flaws.*

---

== Item 19: Design and document for inheritance or else prohibit it

Designing a class for inheritance is hard work. One must document all of its *self-use patterns*, and once documented them, must commit to them for the life of the class. 

---

== Item 20: Prefer interfaces to abstract classes
* Java has two mechanisms to define a type that permits multiple implementations: *interfaces* and *abstract* classes. 
* Since the introduction of *default methods* for interfaces in *Java 8*, both mechanisms allow *to provide implementations for some instance methods.* 
* A major difference is that to implement the type defined by an abstract class, *a class must be a subclass of the abstract class*. Because Java permits only single inheritance, this restriction on abstract classes severely constrains their use as type definitions. 

Any class that defines all the required methods and obeys the general contract is permitted to implement an interface, regardless of where the class resides in the class hierarchy.

* *Existing classes can easily be retrofitted to implement a new interface.*

* *Interfaces are ideal for defining mixins*. a mixin is a type that a class can implement in addition to its “primary type,” to declare that it provides some optional behavior. 

* *Interfaces allow for the construction of nonhierarchical type frameworks.* Type hierarchies are great for organizing some things, but other things don’t fall neatly into a rigid hierarchy.

* *Interfaces enable safe, powerful functionality enhancements via the wrapper class idiom* (Item 18). If you use abstract classes to define types, you leave the programmer who wants to add functionality with no alternative but inheritance. The resulting classes are less powerful and more fragile than wrapper classes.

[NOTE]
====
When there is an obvious implementation of an interface method in terms of other interface methods, consider providing implementation assistance to programmers in the form of a default method. ex `removeIf` default implementations in `collection` interface.
====


* One can, however, combine the advantages of interfaces and abstract classes by providing an abstract *skeletal implementation* class to go with an interface. The interface defines the type, perhaps providing some default methods, while the skeletal implementation class implements the remaining non-primitive interface methods atop the primitive interface methods. Extending a skeletal implementation takes most of the work out of implementing an interface. *This is the Template Method pattern* [Gamma95].

* By convention, skeletal implementation classes are called *AbstractInterface*, where Interface is the name of the interface they implement. For example, the Collections Framework provides a skeletal implementation to go along with each main collection interface: `AbstractCollection`, `AbstractSet`, `AbstractList`, and `AbstractMap`. 

* The beauty of skeletal implementation classes is that they provide all of the implementation assistance of abstract classes without imposing the severe constraints that abstract classes impose when they serve as type definitions. For most implementors of an interface with a skeletal implementation class, extending this class is the obvious choice, but it is strictly optional. If a class cannot be made to extend the skeletal implementation, the class can always implement the interface directly. The class still benefits from any default methods present on the interface itself. 

* The skeletal implementation can still aid the implementor’s task. The class implementing the interface can forward invocations of interface methods to a contained instance of a private inner class that extends the skeletal implementation. This technique, known as *simulated multiple inheritance*, is closely related to the wrapper class idiom discussed in Item 18. It provides many of the benefits of multiple inheritance, while avoiding the pitfalls.

---
== Item 21: Design interfaces for posterity
* Prior to Java 8, it was impossible to add methods to interfaces without breaking existing implementations. In Java 8, the *default method construct* was added [JLS 9.4], with the intent of allowing the addition of methods to existing interfaces. But adding new methods to existing interfaces is fraught with risk.

* The declaration for a default method includes a default implementation that is used by all classes that implement the interface but do not implement the default method. While the addition of default methods to Java makes it possible to add methods to an existing interface, there is no guarantee that these methods will work in all preexisting implementations. 
* *Default methods* are “injected” into existing implementations without the knowledge or consent of their implementors. Before Java 8, these implementations were written with the tacit understanding that their interfaces would never acquire any new methods.

* Using *default methods* to add new methods to existing interfaces should be avoided unless the need is critical, in which case you should think long and hard about whether an existing interface implementation might be broken by your default method implementation. 
* Default methods are, however, extremely useful for providing standard method implementations when an interface is created, to ease the task of implementing the interface (Item 20).

---

== Item 22: Use interfaces only to define types
* When a class implements an interface, the *interface serves as a type* that can be used to refer to instances of the class. That a class implements an interface should therefore say something about what a client can do with instances of the class. It is inappropriate to define an interface for any other purpose.

* One kind of interface that fails this test is the so-called *constant interface*. Such an interface contains no methods; it consists solely of `static` `final` fields, each exporting a constant. Classes using these constants implement the interface to avoid the need to qualify constant names with a class name.

[source,java]
----

// Constant interface antipattern - do not use!
public interface PhysicalConstants {
    // Avogadro's number (1/mol)
    static final double AVOGADROS_NUMBER   = 6.022_140_857e23;

    // Boltzmann constant (J/K)
    static final double BOLTZMANN_CONSTANT = 1.380_648_52e-23;

    // Mass of the electron (kg)
    static final double ELECTRON_MASS      = 9.109_383_56e-31;
}
----

* The constant interface pattern is a poor use of interfaces and should be avoided.

---

== Item 23: Prefer class hierarchies to tagged classes

[source,java]
----

// Tagged class - vastly inferior to a class hierarchy!
class Figure {
    enum Shape { RECTANGLE, CIRCLE };

    // Tag field - the shape of this figure
    final Shape shape;

    // These fields are used only if shape is RECTANGLE
    double length;
    double width;

    // This field is used only if shape is CIRCLE
    double radius;

    // Constructor for circle
    Figure(double radius) {
        shape = Shape.CIRCLE;
        this.radius = radius;
    }

    // Constructor for rectangle
    Figure(double length, double width) {
        shape = Shape.RECTANGLE;
        this.length = length;
        this.width = width;
    }

    double area() {
        switch(shape) {
          case RECTANGLE:
            return length * width;
          case CIRCLE:
            return Math.PI * (radius * radius);
          default:
            throw new AssertionError(shape);
        }
    }
}
----

* Such *tagged classes* have numerous shortcomings. 
* *Tagged classes are verbose, error-prone, and inefficient.*
* *A tagged class is just a pallid imitation of a class hierarchy.*

--- 
== Item 24: Favor static member classes over nonstatic
* A nested class is a class defined within another class. A nested class should exist only to serve its enclosing class. If a nested class would be useful in some other context, then it should be a top-level class. 

* There are four kinds of nested classes: 
** static member classes, (Also known as inner class)
** nonstatic member classes, 
** anonymous classes, and 
** local classes. 

* A static member class is the simplest kind of nested class. It is best thought of as an ordinary class that happens to be declared inside another class and has access to all of the enclosing class’s members, even those declared private. A static member class is a static member of its enclosing class and obeys the same accessibility rules as other static members. If it is declared private, it is accessible only within the enclosing class, and so forth.

* *One common use of a nonstatic member class is to define an Adapter [Gamma95] that allows an instance of the outer class to be viewed as an instance of some unrelated class.* 
For example, implementations of the Map interface typically use nonstatic member classes to implement their collection views, which are returned by Map’s keySet, entrySet, and values methods. 
[source,java]
----
Click here to view code image

// Typical use of a nonstatic member class
public class MySet<E> extends AbstractSet<E> {
    ... // Bulk of the class omitted

    @Override public Iterator<E> iterator() {
        return new MyIterator();
    }

    private class MyIterator implements Iterator<E> {
        ...
    }
}
----


* If a nested class needs to be visible outside of a single method or is too long to fit comfortably inside a method, use a member class. If each instance of a member class needs a reference to its enclosing instance, make it nonstatic; otherwise, make it static. Assuming the class belongs inside a method, if you need to create instances from only one location and there is a preexisting type that characterizes the class, make it an anonymous class; otherwise, make it a local class.

---

== Item 25: Limit source files to a single top-level class

* While the Java compiler lets you define multiple top-level classes in a single source file, there are no benefits associated with doing so, and there are significant risks. The risks stem from the fact that defining multiple top-level classes in a source file makes it possible to provide multiple definitions for a class. Which definition gets used is affected by the order in which the source files are passed to the compiler.

[IMPORTANT]
====
*Never put multiple top-level classes or interfaces in a single source file.* 
====
