= Maven
:navtitle: Maven
:description: 


== https://maven.apache.org/what-is-maven.html[Maven]:

**Maven**, a Yiddish word meaning accumulator of knowledge, began as an attempt to simplify the build processes in the Jakarta Turbine project.

=== Maven's Objectives:
Maven's primary goal is to allow a developer to comprehend the complete state of a development effort in the shortest period of time. In order to attain this goal, 

Maven deals with several areas of concern:

1. Making the build process easy
2. Providing a uniform build system
3. Providing quality project information
4. Encouraging better development practices
5. Making the build process easy
6. While using Maven doesn't eliminate the need to know about the underlying mechanisms, Maven does shield developers from many details.

=== Providing quality project information:
Maven provides useful project information that is in part taken from your POM and in part generated from your project's sources. For example, Maven can provide:

1. Change log created directly from source control
2. Cross referenced sources
3. Mailing lists managed by the project
4. Dependencies used by the project
5. Unit test reports including coverage
6. Third party code analysis products also provide Maven plugins that add their reports to the standard information given by Maven.

=== Providing guidelines for best practices development
Maven aims to gather current principles for best practices development and make it easy to guide a project in that direction.
For example, specification, execution, and reporting of unit tests are part of the normal build cycle using Maven. Current unit testing best practices were used as guidelines:

Keeping test source code in a separate, but parallel source tree
Using test case naming conventions to locate and execute tests
Having test cases setup their environment instead of customizing the build for test preparation
Maven also assists in project workflow such as release and issue management.

Some Common Command Line:

For Creating new project:

```
mvn -B archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4

```
The above code will create a `pom.xml` which have below information:

`pom.xml` contains the **Project Object Model (POM)** for this project. The **POM** is the basic unit of work in Maven which contains every important piece of information about the project and is essentially one-stop-shopping for finding anything related to your project.

Sample `pom.xml`

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
 
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <version>1.0-SNAPSHOT</version>
 
  <name>my-app</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>
 
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>
 
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
 
  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
       ... lots of helpful plugins
    </pluginManagement>
  </build>
</project>

```

1. `project` This is the top-level element in all Maven `pom.xml` files.
2. `modelVersion` This element indicates what version of the object model this POM is using. The version of the model itself changes very infrequently but it is mandatory in order to ensure stability of use if and when the Maven developers deem it necessary to change the model.
3. `groupId` This element indicates the unique identifier of the organization or group that created the project. 
4. `artifactId` This element indicates the unique base name of the primary artifact being generated by this project. The primary artifact for a project is typically a JAR file. 
5. `name` This element indicates the display name used for the project. This is often used in Maven's generated documentation.
6. `url` This element indicates where the project's site can be found. This is often used in Maven's generated documentation.
7. `properties` This element contains value placeholders accessible anywhere within a POM.
8. `dependencies` This element's children list dependencies. The cornerstone of the POM.
9. `build` This element handles things like declaring your project's directory structure and managing plugins.


== https://maven.apache.org/guides/mini/guide-naming-conventions.html[Maven Naming Conventions]:
`groupId` uniquely identifies project across all projects. A **group ID** should follow Java's package name rules. This means it starts with a reversed domain name you control. For example,
org.apache.maven, org.apache.commons

`artifactId` is the name of the jar without version. It can be any name with lowercase letters and no strange symbols. If it's a third party jar, need to take the name of the jar as it's distributed.
eg. maven, commons-math

`version` if need to distribute it, then choose any typical version with numbers and dots (1.0, 1.1, 1.0.1, ...).

== https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference[Maven Build Life Cycle]:

=== Build Lifecycle Basics
Maven is based around the central concept of a build lifecycle. What this means is that the process for building and distributing a particular artifact (project) is clearly defined.

There are three built-in build lifecycles: 
    * **default**: The `default` lifecycle handles your project deployment, 
    * **clean**: the `clean` lifecycle handles project cleaning, 
    * **site**: the `site` lifecycle handles the creation of your project's web site.

=== A Build Lifecycle is Made Up of Phases
Each of these build lifecycles is defined by a different list of build phases, wherein a build phase represents a stage in the lifecycle.

For example, the `default` lifecycle comprises of the following phases:

1. **validate** - validate the project is correct and all necessary information is available
2. **compile** - compile the source code of the project
3. **test** - test the compiled source code using a suitable unit testing framework. These tests should not require the code be packaged or deployed
4. **package** - take the compiled code and package it in its distributable format, such as a JAR.
5. **verify** - run any checks on results of integration tests to ensure quality criteria are met
6. **install** - install the package into the local repository, for use as a dependency in other projects locally
7. **deploy** - done in the build environment, copies the final package to the remote repository for sharing with other developers and projects.

These lifecycle phases (plus the other lifecycle phases not shown here) are executed sequentially to complete the default lifecycle. 

**Usual Command Line Calls**

```
mvn verify
```

This command executes each default lifecycle phase in order (`validate`, `compile`, `package`, etc.), before executing `verify`. You only need to call the last build phase to be executed.