= Richardson Maturity Model
:navtitle: Richardson Maturity Model
:description: Richardson Maturity Model

== Richardson Maturity Model
The *Richardson Maturity Model* is a framework for evaluating the maturity of web services in terms of their adherence to RESTful principles. *Leonard Richardson* analyzed a hundred different web service designs and divided these designs into four categories. These categories are based on how much the web services are REST compliant.

<<TO DO need to add diagram>>

=== Level 0
*Level Zero* represents the most basic form of building service-oriented applications.
The services at zero maturity level have a *single URI* and use a *single HTTP method (mostly POST)*.

[IMPORTANT]
====
.*Level 0*
Does not make use of any of *URI*, *HTTP Methods*, and *HATEOAS* capabilities.
====

Ex: *SOAP Web Services* use a single URI to identify an endpoint, and HTTP POST to transfer SOAP-based payloads, effectively ignoring the rest of the HTTP verbs.

Similarly, *XML-RPC-based* services send data as Plain Old XML (POX).

These are the most primitive ways of building SOA applications with a single POST method endpoint and using XML to communicate between the client and the server.

=== Level 1 - Resource

At this level, services offer *multiple URIs* to represent various resources within the system, but they typically use a single HTTP verb, often POST, for interactions. Each resource is identified by a unique URI, enhancing the design compared to Level Zero.

[IMPORTANT]
====
.*Level 1*
Makes use of *URIs*, but *does not use* the *HTTP Methods*, and *HATEOAS*.
====

=== Level 2 - HTTP Verbs
The level two services generally host numerous URIs i.e. addressable resources. Such services support several of the HTTP verbs on each exposed resource – Create, Read, Update, and Delete (CRUD) services. Here the state of resources, typically representing business entities, can be manipulated over the network.

[IMPORTANT]
====
.*Level 2*
*makes use* of *URIs* and *HTTP Methods*, but *does not use* the *HATEOAS*.
====

=== Level 3 - Hypermedia Controls

At level three, services prioritize easy discoverability and self-descriptiveness. This level makes it easy for the responses to be self-descriptive by using HATEOAS (Hypertext As The Engine Of Application State). By utilizing HATEOAS, clients can navigate and understand the service without relying extensively on external documentation.

[IMPORTANT]
====
.*Level 3*
*makes use* of all three, i.e. *URIs* and *HTTP*, and *HATEOAS*.
====

*Benefit of hypermedia controls* 

*. It allows the server to change its URI scheme without breaking clients. As long as clients look up the "addTest" link URI then the server team can juggle all URIs other than the initial entry points.

*. It helps client developers explore the protocol. The links give client developers a hint as to what may be possible next. It doesn't give all the information: both the "self" and "cancel" controls point to the same URI - they need to figure out that one is a GET and the other a DELETE. But at least it gives them a starting point as to what to think about for more information and to look for a similar URI in the protocol documentation.

*. Similarly it allows the server team to advertise new capabilities by putting new links in the responses. If the client developers are keeping an eye out for unknown links these links can be a trigger for further exploration.

<<Code Example Java Get a cup of coffee>>